<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/09 19:10:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'Rebeka02',
  'name' => 'doctrine',
)),);
