<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/09 18:12:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobbet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
